// Package agentsdk provides a thin, runtime-neutral SDK for managed Agents to
// make nested invocations through the NeKiro A2A Router. It validates inherited
// platform context and sends exactly one request to the Agent Router v1
// boundary. It contains no model, tool, workflow, memory, retry, cache, or
// Agent Runtime behavior.
package agentsdk

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"

	"github.com/Nene7ko/NeKiro/contracts"
)

// PlatformContext carries the trusted inherited Invocation identity presented
// by the managed transport. All fields are required safe identifiers; no value
// is inferred or synthesized.
type PlatformContext struct {
	InvocationID string
	RootTaskID   string
	TraceID      string
	WorkspaceID  string
	AgentID      string
}

// Validate checks that all PlatformContext fields are present and safe
// identifiers. It fails without synthesizing identity or correlation.
func (pc PlatformContext) Validate() error {
	fields := []struct {
		name  string
		value string
	}{
		{"invocationId", pc.InvocationID},
		{"rootTaskId", pc.RootTaskID},
		{"traceId", pc.TraceID},
		{"workspaceId", pc.WorkspaceID},
		{"agentId", pc.AgentID},
	}
	for _, field := range fields {
		if field.value == "" {
			return fmt.Errorf("agentsdk: platform context %s is required", field.name)
		}
		if !safeIdentifier(field.value) {
			return fmt.Errorf("agentsdk: platform context %s is invalid", field.name)
		}
	}
	return nil
}

// NestedRequest carries the untrusted target work for a nested invocation.
// It contains only the fields permitted by the Agent Router v1 contract.
type NestedRequest struct {
	TargetAgentID string
	Capability    string
	Input         json.RawMessage
	Stream        bool
}

// Validate checks that the NestedRequest fields are present and safe.
func (nr NestedRequest) Validate() error {
	if nr.TargetAgentID == "" {
		return errors.New("agentsdk: targetAgentId is required")
	}
	if !safeIdentifier(nr.TargetAgentID) {
		return errors.New("agentsdk: targetAgentId is invalid")
	}
	if nr.Capability == "" {
		return errors.New("agentsdk: capability is required")
	}
	if !safeIdentifier(nr.Capability) {
		return errors.New("agentsdk: capability is invalid")
	}
	if nr.Input == nil {
		return errors.New("agentsdk: input is required")
	}
	var inputObj map[string]json.RawMessage
	if err := json.Unmarshal(nr.Input, &inputObj); err != nil || inputObj == nil {
		return errors.New("agentsdk: input must be a JSON object")
	}
	return nil
}

// NestedResult carries the response from a successful nested invocation.
type NestedResult struct {
	// InvocationID is the child Invocation ID generated by the Router.
	InvocationID string
	// RootTaskID is the inherited root Task from the parent.
	RootTaskID string
	// TraceID is the inherited Trace from the parent.
	TraceID string
	// Status is the terminal status of the child invocation.
	Status string
	// Result is the raw JSON result for non-streaming calls.
	Result json.RawMessage
	// Body is the raw response body (for SSE streaming, this is the full stream).
	Body []byte
}

// HTTPDoer is the minimal HTTP transport interface. The SDK performs exactly
// one request and does not follow redirects or retry.
type HTTPDoer interface {
	Do(*http.Request) (*http.Response, error)
}

// Client is a thin SDK client for nested Router calls. It validates inherited
// platform context and sends exactly one request to the configured Agent
// Router v1 origin.
type Client struct {
	doer      HTTPDoer
	routerURL string
	token     string
}

// NewClient creates a nested invocation SDK client. The routerURL must be the
// explicit Agent Router v1 origin (e.g. "https://router.example.dev"). The
// token is the opaque bearer credential bound to exactly one Agent ID.
// The doer must not follow redirects; if it is an *http.Client, the SDK
// disables redirects.
func NewClient(doer HTTPDoer, routerURL, token string) (*Client, error) {
	if doer == nil {
		return nil, errors.New("agentsdk: HTTP doer is required")
	}
	if routerURL == "" {
		return nil, errors.New("agentsdk: router URL is required")
	}
	if token == "" {
		return nil, errors.New("agentsdk: bearer token is required")
	}
	if httpClient, ok := doer.(*http.Client); ok {
		client := *httpClient
		client.CheckRedirect = func(*http.Request, []*http.Request) error {
			return http.ErrUseLastResponse
		}
		doer = &client
	}
	return &Client{doer: doer, routerURL: routerURL, token: token}, nil
}

// Invoke sends one nested invocation request to the Agent Router v1 boundary.
// It validates the platform context and request locally before sending. On
// malformed or incomplete context, it fails without synthesizing identity or
// correlation. It performs exactly one request and does not retry or follow
// redirects.
func (c *Client) Invoke(ctx context.Context, pc PlatformContext, nr NestedRequest) (*NestedResult, error) {
	if err := pc.Validate(); err != nil {
		return nil, err
	}
	if err := nr.Validate(); err != nil {
		return nil, err
	}

	body := contracts.NestedInvocationRequestV1{
		ParentInvocationID: pc.InvocationID,
		TargetAgentID:      nr.TargetAgentID,
		Capability:         nr.Capability,
		Input:              nr.Input,
		Stream:             nr.Stream,
	}
	payload, err := json.Marshal(body)
	if err != nil {
		return nil, fmt.Errorf("agentsdk: encode nested request: %w", err)
	}

	accept := "application/json"
	if nr.Stream {
		accept = "text/event-stream"
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, c.routerURL+"/agent/v1/invocations", bytes.NewReader(payload))
	if err != nil {
		return nil, fmt.Errorf("agentsdk: construct nested request: %w", err)
	}
	req.Header.Set("Authorization", "Bearer "+c.token)
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", accept)

	resp, err := c.doer.Do(req)
	if err != nil {
		return nil, fmt.Errorf("agentsdk: nested request failed: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("agentsdk: read nested response: %w", err)
	}

	if resp.StatusCode != http.StatusOK {
		return nil, &RouterError{StatusCode: resp.StatusCode, Body: respBody}
	}

	result := &NestedResult{Body: respBody}
	if !nr.Stream {
		var invocationResult contracts.InvocationResult
		if err := json.Unmarshal(respBody, &invocationResult); err != nil {
			return nil, fmt.Errorf("agentsdk: decode nested result: %w", err)
		}
		result.InvocationID = invocationResult.InvocationID
		result.RootTaskID = invocationResult.RootTaskID
		result.TraceID = string(invocationResult.TraceID)
		result.Status = invocationResult.Status
		result.Result = invocationResult.Result
	}
	return result, nil
}

// RouterError represents a non-200 response from the Agent Router.
type RouterError struct {
	StatusCode int
	Body       []byte
}

func (e *RouterError) Error() string {
	return fmt.Sprintf("agentsdk: router returned status %d", e.StatusCode)
}

// safeIdentifier validates that a string is a safe platform identifier
// matching the pattern ^[A-Za-z0-9](?:[A-Za-z0-9._:-]{0,127})$.
func safeIdentifier(value string) bool {
	if len(value) < 1 || len(value) > 128 {
		return false
	}
	for index, character := range []byte(value) {
		if character >= 'A' && character <= 'Z' || character >= 'a' && character <= 'z' || character >= '0' && character <= '9' || character == '.' || character == '_' || character == ':' || character == '-' {
			if index > 0 || character != '.' && character != '_' && character != ':' && character != '-' {
				continue
			}
		}
		return false
	}
	return true
}
